config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq' if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  devise_for :users

  root to: 'recipes#index'

  resources :recipes do
    resources :assessments, only: [:new, :create, :edit, :update]
  end

  resources :revenges, only: [:index]

  resources :nocreateds, only: [:index]

  resources :searches, only: [:index]

  resources :search_results, only: [:index]


  namespace :categorys do
    resource :rice, only: [:show]
    resource :soup, only: [:show]
    resource :main, only: [:show]
    resource :side, only: [:show]
    resource :dessert, only: [:show]
    resource :others, only: [:show]
  end

  resource :contact, only: [:new, :create]

end

app/models/recipe.rb
# == Schema Information
#
# Table name: recipes
#
#  id         :bigint           not null, primary key
#  content    :text
#  info       :text
#  title      :string           not null
#  url        :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_recipes_on_user_id  (user_id)
#
class Recipe < ApplicationRecord
    
    validates :title, presence: true, length: {maximum: 25}

    belongs_to :user
    has_many :recipe_categorys
    has_many :categories, through: :recipe_categorys, dependent: :destroy
    has_one :assessment, dependent: :destroy

    def get_category_ids(category_ids, recipe)
        if category_ids.size >= 2
            category_ids.shift
            category_ids.each do |category_id|
                category = Category.find(category_id.to_i)
                recipe.categories << category
            end
        end
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
    before_action :authenticate_user!

    def index
        @recipes = current_user.recipes.all.order(created_at: :DESC)
    end

    def show
        @recipe = current_user.recipes.find(params[:id])
    end

    def new
        @recipe = current_user.recipes.build
    end

    def create
        @recipe = current_user.recipes.build(recipe_params)
        @category_ids = params[:recipe][:categories]
        if @recipe.save
            @recipe.get_category_ids(@category_ids, @recipe)
            
            redirect_to root_path
        else
            render :new
        end
    end

    def edit
        @recipe = current_user.recipes.find(params[:id])
        @category_ids = @recipe.categories.pluck(:id)
    end

    def update
        @recipe = current_user.recipes.find(params[:id])
        @category_ids = params[:recipe][:categories]
        if @recipe.update(recipe_params)
            RecipeCategory.where(recipe_id: @recipe.id).destroy_all
            @recipe.get_category_ids(@category_ids, @recipe)

            redirect_to recipe_path
        else
            render :edit
        end
    end

    def destroy
        recipe = Recipe.find(params[:id])
        recipe.destroy!
        redirect_to root_path
    end

    private
        def recipe_params
            params.require(:recipe).permit(:title, :url, :info, :content)
        end
end

app/views/recipes/edit.html.haml
= render 'commons/header'
.container
  = render 'commons/errors', model: @recipe
  = form_with(model: @recipe, local: true) do |f|
    %div
      = f.label :title, '料理名', class: 'item'
    %div
      = f.text_field :title, class: 'text'
    %div
      = f.label :url, 'URL', class: 'item'
    %div
      = f.text_field :url, class: 'text'
    %div
      = f.label :info, 'URL情報', class: 'item'
    %div
      = f.text_area :info, class: 'text_info'
    %div
      = f.label :content, 'メモ', class: 'item'
    %div
      = f.text_area :content, class: 'text_content'
    %div
      = f.label :category, 'カテゴリー', class: 'category-item'
    %div.checkbox
      = f.collection_check_boxes :categories, Category.all, :id, :foodclass, { checked: @category_ids.map(&:to_param) }

    .active
      = f.submit 'update', class: 'btn, active-btn'
    .cancel
      = link_to 'cancel', recipe_path, class: 'cancel_btn' 

= render 'commons/footer'

app/views/recipes/index.html.haml
= render 'commons/index', recipes: @recipes

app/views/recipes/new.html.haml
= render 'commons/header'
.container
  = render 'commons/errors', model: @recipe
  = form_with(model: @recipe, local: true) do |f|
    %div
      = f.label :title, '料理名', class: 'item'
    %div
      = f.text_field :title, class: 'text', placeholder: ' 例) 悪魔の唐揚げ'
    %div
      = f.label :url, 'URL', class: 'item'
    %div
      = f.text_field :url, class: 'text', placeholder: ' 例) https://twitter.com/marumi_kitchen/status/1508368297863000069?s=21'
    %div
      = f.label :info, 'URL情報', class: 'item'
    %div
      = f.text_area :info, class: 'text_info', placeholder: ' 例) まるみキッチン【簡単レシピ】さんのツイート'
    %div
      = f.label :content, 'メモ', class: 'item'
    %div
      = f.text_area :content, class: 'text_content', placeholder: ' 例) 炊飯器で一発!めちゃくちゃ簡単'
    %div
      = f.label :category, 'カテゴリー', class: 'category-item'
    %div.checkbox
      = f.collection_check_boxes :categories, Category.all, :id, :foodclass

    .active
      = f.submit 'submit', class: 'active-btn'
    .cancel
      = link_to 'cancel', recipes_path, class: 'cancel_btn' 

= render 'commons/footer'

app/views/recipes/show.html.haml
= render 'commons/header'
.container#recipe{ date: {recipe_id: @recipe.id} }
  .recipe-row
    .recipe-intro
      .recipe-title
        %h2= @recipe.title
      .recipe-url
        = link_to 'リンク先', @recipe.url, target: :_blank, rel: 'noopener noreferrer'
        .recipe-info
          %span= @recipe.info
      .recipe-content
        %p= @recipe.content
  .btn-action
    .assessment_show_btn
      - if @recipe.assessment.present?
        %p.assessment_btn 再評価
      - else
        %p.assessment_btn 評価
    = link_to '編集', edit_recipe_path, class: 'edit-btn'
    = link_to '削除', recipe_path(@recipe.id), data: { method: 'delete', confirm: '本当に削除しますか' }, class: 'edit-btn'

  - if @recipe.assessment.present?
    .assessment
      %p 美味しさ
      .star-vlaue#star-taste1
      %p 作りやすさ
      .star-vlaue#star-taste2
      %p 費用
      .star-vlaue#star-taste3

    = render 'commons/star_assessment/show'
  
  .assessment_show.hidden
    - if @recipe.assessment.present?
      = form_tag(recipe_assessment_path(recipe_id: @recipe.id, id: @recipe.assessment.id), method: :put) do
        .assessment_form
          %div
            = label :taste, '美味しさ'
          %div.starform#star-taste
            = hidden_field_tag :taste, id: :review_star
          %div
            = label :easily, '作りやすさ'
          %div.starform#star-easily
            = hidden_field_tag :easily, id: :review_star  
          %div
            = label :cost, '費用'
          %div.starform#star-cost
            = hidden_field_tag :cost, id: :review_star  
          %div
            = label :revenge, '再挑戦', class: 'app_checkbox'
          - if @recipe.assessment.revenge.blank?
            %div.app_checkbox
              = check_box_tag :revenge, true
              %label{:for => 'revenge'}
          -else
            %div.app_checkbox
              = check_box_tag :revenge, true, checked = 'checked'
              %label{:for => 'revenge'}          
          .active
            = submit_tag 'edit', class: 'assessment_active_btn'
          .cancel
            %p.cancel_btn cancel

          = render 'commons/star_assessment/edit'

    -else
      = form_tag(recipe_assessments_path(@recipe.id), method: :post) do
        .assessment_form
          %div
            = label :taste, '美味しさ'
          %div.starform#star-taste
            = hidden_field_tag :taste, id: :review_star
          %div
            = label :easily, '作りやすさ'
          %div.starform#star-easily
            = hidden_field_tag :easily, id: :review_star  
          %div
            = label :cost, '費用'
          %div.starform#star-cost
            = hidden_field_tag :cost, id: :review_star  
          %div
            = label :revenge, '再挑戦', class: 'app_checkbox'
          %div.app_checkbox
            = check_box_tag :revenge, true, false
            %label{:for => 'revenge'}

          .active
            = submit_tag 'submit', class: 'assessment_active_btn'
          .cancel
            %p.cancel_btn cancel

          = render 'commons/star_assessment/new'


= render 'commons/footer'