config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq' if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  devise_for :users

  root to: 'recipes#index'

  resources :recipes do
    resources :assessments, only: [:new, :create, :edit, :update]
  end

  resources :revenges, only: [:index]

  resources :nocreateds, only: [:index]

  resources :searches, only: [:index]

  resources :search_results, only: [:index]


  namespace :categorys do
    resource :rice, only: [:show]
    resource :soup, only: [:show]
    resource :main, only: [:show]
    resource :side, only: [:show]
    resource :dessert, only: [:show]
    resource :others, only: [:show]
  end

  resource :contact, only: [:new, :create]

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
    before_action :authenticate_user!

    def index
    end

end

app/views/searches/index.html.haml
= render 'commons/header'
.container
  .search_form
    = form_with(url: search_results_path, method: 'GET', local: true) do |f|
      = f.text_field :word, class: 'search_text'
      = f.submit '検索'

  .category_images
    .rice.bg
      = link_to categorys_rice_path do
        %i.fa-solid.fa-bowl-rice.icon
        %p Rice
    .soup.bg
      = link_to categorys_soup_path do
        %i.fa-solid.fa-mug-hot.icon
        %p Soup
    .main.bg
      = link_to categorys_main_path do
        %i.fa-solid.fa-pizza-slice.icon
        %p Main
    .side.bg
      = link_to categorys_side_path do
        %i.fa-solid.fa-carrot.icon
        %p side
    .dessert.bg
      = link_to categorys_dessert_path do
        %i.fa-solid.fa-cake-candles.icon
        %p dessert
    .other.bg
      = link_to categorys_others_path do
        %i.fa-solid.fa-utensils.icon
        %p others
= render 'commons/footer'

app/views/searches/show.html.haml
ああああああ